### ISSUE TITLE
Idnits: 

### ISSUE THREAD

**Issue by boucadair** [boucadair/5g-slice-realization#65]
== There are 867 instances of lines with non-ascii characters in the
     document.

  == The page length should not exceed 58 lines per page, but there was 1
     longer page, the longest (page 1) being 3235 lines

see more at [https://[author-tools.ietf.org/api/idnits?url=https://boucadair.github.io/5g-slice-realization/draft-ietf-teas-5g-ns-ip-mpls.txt&submissioncheck=True](https://author-tools.ietf.org/api/idnits?url=https://boucadair.github.io/5g-slice-realization/draft-ietf-teas-5g-ns-ip-mpls.txt&submissioncheck=True)](https://author-tools.ietf.org/api/idnits?url=https://boucadair.github.io/5g-slice-realization/draft-ietf-teas-5g-ns-ip-mpls.txt&verbose=2&submissioncheck=True)

Reduced the warnings by touching manually some figures, but there is a lot of work to be done to make idnits happy.

**Comment by boucadair** [comment]
Made some changes to the figures but still lot to do: 

  == There are 860 instances of lines with non-ascii characters in the
     document.

**Comment by boucadair** [comment]
@kszarkowicz will make the arguments.

**Comment by kszarkowicz** [comment]
Unicode is for diagrams is allowed format (https://authors.ietf.org/en/diagrams):

"[asciiflow](https://asciiflow.com/#/) is a web based interactive ASCII diagramming tool. It support both ASCII and extended Unicode box drawing characters. asciiflow only exports as text."

"[Monodraw](https://monodraw.helftone.com/) is an interactive ASCII diagramming tool that support both ASCII and extended Unicode box drawing characters."

The problem is not with the Unicode diagrams included in the draft. The problem is with false negative generated by idnits tool. Namely, idnits tool considers single, 16 bit long Unicode character as two, 8 bit characters. Therefore, the character length in the lines containing Unicode characters is doubled.

Further, idnits tool, of detects CR and/or LF in one of the two octet long of Unicode character, considers this a new line, generating false negative that number of lines per page exceeds 58 lines.

They way forward, thus, is to fix issues withg idnits, as the Unicode diagrams in the draft are correct.

**Comment by kszarkowicz** [comment]
Adding to that, xml2rfc (https://github.com/ietf-tools/xml2rfc) properly renders Unicode diagrams without generating false negatives.
